apiVersion: v1
kind: Pod
metadata:
  name: before
spec:
  containers:
  - name: c
    image: before-the-break:1.0
---
apiVersion: v1
kind: Pod
metadata:
  name: broken
spec:
  containers:
  - name: c
    image: nginx
    ports: [8080
---
apiVersion: v1
kind: Pod
metadata:
  name: after
spec:
  containers:
  - name: c
    image: after-the-break:1.0
