apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
    - name: myapp
      image: nginx
  initContainers:
    - name: init-mysidecar
      image: gcr.io/google-containers/sidecar
      restartPolicy: Always
