# Build context is assembled by GoReleaser: the pre-built `kir` binary for the
# target platform is copied in, so there is no build step here.
FROM gcr.io/distroless/static:nonroot@sha256:e2e927ec666bae08560abb3c55d0659eceabb657f56b6782ab500a9fc7f555e3
WORKDIR /
COPY kir /kir
USER 65532:65532
ENTRYPOINT ["/kir"]
