# Build context is assembled by GoReleaser: the pre-built `kir` binary for the
# target platform is copied in, so there is no build step here.
FROM gcr.io/distroless/static:nonroot@sha256:f7f8f729987ad0fdf6b05eeeae94b26e6a0f613bdf46feea7fc40f7bd72953e6
WORKDIR /
COPY kir /kir
USER 65532:65532
ENTRYPOINT ["/kir"]
