name: Go Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - id: go-version
        run: |
          echo "go-version=$(cat .tool-versions | grep golang | cut -d ' ' -f 2)" >> "$GITHUB_OUTPUT"

      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: ${{ steps.go-version.outputs.go-version }}

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./...
